# generated by datamodel-codegen:
#   filename:  agent-output-content.schema.json
#   timestamp: 2026-03-24T13:05:30+00:00

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class StringTemplate(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Prose string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.\n',
            min_length=5,
            pattern='\\{\\{[a-zA-Z_]+\\}\\}',
            title='StringTemplate',
        ),
    ]


class StringText(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Natural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.\n',
            min_length=10,
            pattern='\\s',
            title='StringText',
        ),
    ]


class StringProse(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Substantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.\n',
            min_length=20,
            pattern='^[A-Z](?:.*?\\s){3,}.*[.!?;:]$',
            title='StringProse',
        ),
    ]


class IdentityContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringTemplate,
        Field(
            description="Section heading for identity. Template with {{title}} placeholder for the agent's display title. Rendered as H2 (or H3 inside a group). Position: first element of the section.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.",
            title='IdentityHeading',
        ),
    ]
    declaration: Annotated[
        StringTemplate,
        Field(
            description='Core identity declaration. Template with {{role_identity}} placeholder. Establishes who the agent is — the foundational sentence that frames all subsequent behavior. Position: immediately after heading.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='IdentityDeclaration',
        ),
    ]
    declaration_heuristic_postscript: Annotated[
        StringTemplate,
        Field(
            description='Reinforcement postscript after the identity declaration. Template with {{role_identity}} placeholder. Anchors decision-making to the declared identity. Position: after declaration, before responsibility.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='IdentityDeclarationHeuristicPostscript',
        ),
    ]
    responsibility_label: Annotated[
        StringTemplate,
        Field(
            description="Label introducing the agent's responsibility scope. Template with {{role_responsibility}} placeholder. Position: label immediately before the responsibility data.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.",
            title='IdentityResponsibilityLabel',
        ),
    ]
    expertise_label: Annotated[
        StringText,
        Field(
            description='Label introducing the expertise list. Plain text (no placeholders). Position: label immediately before the expertise data list.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='IdentityExpertiseLabel',
        ),
    ]
    expertise_is_strictly_limited_postscript: Annotated[
        StringProse,
        Field(
            description="Reinforcement postscript after the expertise list. Constrains the agent's authoritative judgment to the listed areas only. Visibility controlled by identity_expertise_postscript_visible in structure. Position: postscript after expertise data.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.",
            title='IdentityExpertisePostscript',
        ),
    ]
    closing_identity_reminder: Annotated[
        StringTemplate,
        Field(
            description="Optional closing sentence restating the agent's role identity. Template with {{role_identity}} placeholder. Visibility controlled by identity_closing_reminder_visible in structure. Position: last element of the section.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.",
            title='IdentityClosingReminder',
        ),
    ]


class FramingVariantHeading(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    territory: Annotated[
        StringText,
        Field(
            description='Section heading when framing_variant is "territory". Frames the workspace as the agent\'s domain.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FramingVariantHeadingTerritory',
        ),
    ]
    environmental: Annotated[
        StringText,
        Field(
            description='Section heading when framing_variant is "environmental". Frames the workspace as the operating context.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FramingVariantHeadingEnvironmental',
        ),
    ]
    cage: Annotated[
        StringText,
        Field(
            description='Section heading when framing_variant is "cage". Frames the workspace as a confinement boundary.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FramingVariantHeadingCage',
        ),
    ]


class FramingVariantWorkspacePathDeclaration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    territory: Annotated[
        StringTemplate,
        Field(
            description='Workspace path declaration when framing_variant is "territory". Template with {{WORKSPACE_PATH}} placeholder. Frames the path as the agent\'s domain root.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='FramingVariantWorkspacePathDeclarationTerritory',
        ),
    ]
    environmental: Annotated[
        StringTemplate,
        Field(
            description='Workspace path declaration when framing_variant is "environmental". Template with {{WORKSPACE_PATH}} placeholder. Frames the path as the operating environment.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='FramingVariantWorkspacePathDeclarationEnvironmental',
        ),
    ]
    cage: Annotated[
        StringTemplate,
        Field(
            description='Workspace path declaration when framing_variant is "cage". Template with {{WORKSPACE_PATH}} placeholder. Frames the path as a hard confinement boundary.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='FramingVariantWorkspacePathDeclarationCage',
        ),
    ]


class FramingVariantSectionPreamble(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    territory: Annotated[
        StringText,
        Field(
            description='Section preamble when framing_variant is "territory". Introduces the display entries with domain-ownership language.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FramingVariantSectionPreambleTerritory',
        ),
    ]
    environmental: Annotated[
        StringText,
        Field(
            description='Section preamble when framing_variant is "environmental". Introduces the display entries with availability language.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FramingVariantSectionPreambleEnvironmental',
        ),
    ]
    cage: Annotated[
        StringText,
        Field(
            description='Section preamble when framing_variant is "cage". Introduces the display entries with confinement language.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FramingVariantSectionPreambleCage',
        ),
    ]


class FramingVariantContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        FramingVariantHeading,
        Field(
            description='Variant alternatives for the security boundary section heading. Keys match enum/framing_variant values. Structure selects one.',
            title='FramingVariantHeading',
        ),
    ]
    workspace_path_declaration: Annotated[
        FramingVariantWorkspacePathDeclaration,
        Field(
            description='Variant alternatives for the workspace path declaration. Keys match enum/framing_variant values. Structure selects one. Templates contain {{WORKSPACE_PATH}} placeholder.',
            title='FramingVariantWorkspacePathDeclaration',
        ),
    ]
    section_preamble: Annotated[
        FramingVariantSectionPreamble,
        Field(
            description='Variant alternatives for the section preamble introducing display entries. Keys match enum/framing_variant values. Structure selects one.',
            title='FramingVariantSectionPreamble',
        ),
    ]


class SecurityBoundaryContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filesystem_map_intro: Annotated[
        StringText,
        Field(
            description='Introductory line before the filesystem display entries. Plain text with no placeholders. Position: label before the entry list. Visibility controlled by security_boundary_filesystem_map_intro_visible.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='SecurityBoundaryFilesystemMapIntro',
        ),
    ]
    section_closing: Annotated[
        StringProse,
        Field(
            description='Closing statement after the display entries. Instructs the agent on what to do when a needed path is not listed. Position: postscript after the entry list. Visibility controlled by security_boundary_section_closing_visible.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='SecurityBoundarySectionClosing',
        ),
    ]
    compound_entry_template: Annotated[
        StringTemplate,
        Field(
            description='Template for rendering a single display entry when tools are shown per-entry. Contains {{PATH}} and {{TOOLS}} placeholders. Used when tool sets differ across entries (heterogeneous format).\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='SecurityBoundaryCompoundEntryTemplate',
        ),
    ]
    grouped_tool_header: Annotated[
        StringTemplate,
        Field(
            description='Header line when all display entries share the same tool set. Contains {{TOOLS}} placeholder. Rendered once above the entry list when uniform_toolset_format is "grouped".\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='SecurityBoundaryGroupedToolHeader',
        ),
    ]
    framing_variant: Annotated[
        FramingVariantContent,
        Field(
            description='Shared variant content for security boundary framing. Contains three content families (heading, workspace_path_declaration, section_preamble) that all switch together based on the framing_variant selector in structure. Each family is a simplegroup with one field per variant key.',
            title='FramingVariantContent',
        ),
    ]


class CriticalRulesContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for critical rules. Plain text, no placeholders. Rendered as H2. Typically emphatic — all caps or strong language to signal inviolability.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='CriticalRulesHeading',
        ),
    ]
    authority_preamble: Annotated[
        StringProse,
        Field(
            description='Authority establishment before rules are listed. Declares that critical rules override all other instructions and that violation equals task failure. Position: preamble after heading.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='CriticalRulesAuthorityPreamble',
        ),
    ]
    workspace_confinement: Annotated[
        StringTemplate,
        Field(
            description='Workspace confinement rule text. Template with {{workspace_path}} placeholder. Declares that nothing outside the workspace exists.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='CriticalRulesWorkspaceConfinement',
        ),
    ]
    output_tool_exclusivity: Annotated[
        StringTemplate,
        Field(
            description='Output tool exclusivity rule text. Template with {{tool_name}} placeholder. Declares that the named tool is the only output mechanism.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='CriticalRulesOutputToolExclusivity',
        ),
    ]
    batch_discipline: Annotated[
        StringTemplate,
        Field(
            description='Batch discipline rule text. Template with {{batch_size}} and {{tool_name}} placeholders. Requires processing in batches with immediate writes after each batch.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='CriticalRulesBatchDiscipline',
        ),
    ]
    fail_fast: Annotated[
        StringProse,
        Field(
            description='Fail-fast rule text. Instructs the agent to return FAILURE immediately on error. No recovery attempts, no partial data, no working around problems.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='CriticalRulesFailFast',
        ),
    ]
    input_is_your_only_source: Annotated[
        StringProse,
        Field(
            description='Input-only-source rule text. Prohibits supplementing input with external sources, training data, or additional materials. Process what you received and nothing else.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='CriticalRulesInputIsYourOnlySource',
        ),
    ]
    no_invention: Annotated[
        StringProse,
        Field(
            description='No-invention rule text. Requires every claim in output to trace to input. If you cannot point to the source, do not include it. Silence is correct when data is absent.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='CriticalRulesNoInvention',
        ),
    ]
    discipline_over_helpfulness: Annotated[
        StringProse,
        Field(
            description='Discipline-over-helpfulness rule text. Reframes discipline as the helpful behavior — clean FAILURE is more helpful than contaminated success. Experimental rule.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='CriticalRulesDisciplineOverHelpfulness',
        ),
    ]
    rule_count_awareness_prelude: Annotated[
        StringTemplate,
        Field(
            description='Rule count awareness prelude text. Template with {{rule_count}} placeholder. Tells the agent how many inviolable rules follow. Visibility controlled by the auto/threshold mechanism in structure.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='CriticalRulesRuleCountAwarenessPrelude',
        ),
    ]


class InstructionsHeadingVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default: Annotated[
        StringText,
        Field(
            description='Heading text when heading_variant is "default". Plain section heading.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='InstructionsHeadingVariantDefault',
        ),
    ]
    procedure: Annotated[
        StringText,
        Field(
            description='Heading text when heading_variant is "procedure". Uses formal procedural language.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='InstructionsHeadingVariantProcedure',
        ),
    ]
    steps_with_count: Annotated[
        StringTemplate,
        Field(
            description='Heading text when heading_variant is "steps_with_count". Template with {{step_count}} placeholder. Includes total step count in the heading.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsHeadingVariantStepsWithCount',
        ),
    ]


class InstructionsContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instructions_preamble_step_count: Annotated[
        StringTemplate,
        Field(
            description='Step count statement in the preamble. Template with {{step_count}} placeholder. Tells the agent how many steps to expect.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsPreambleStepCount',
        ),
    ]
    instructions_preamble_no_add_skip_reorder: Annotated[
        StringProse,
        Field(
            description='Prohibition against adding, skipping, or reordering steps. Position: preamble component.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='InstructionsPreambleNoAddSkipReorder',
        ),
    ]
    instructions_preamble_exact_vs_judgment_preview: Annotated[
        StringProse,
        Field(
            description='Preview of exact/judgment mode distinction in the preamble. Explains that some steps are mechanical and some require reasoning.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='InstructionsPreambleExactVsJudgmentPreview',
        ),
    ]
    instructions_preamble_no_extra_operations: Annotated[
        StringProse,
        Field(
            description='Prohibition against supplementing steps with general knowledge or adding unspecified operations. Each step is a complete specification.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='InstructionsPreambleNoExtraOperations',
        ),
    ]
    step_header_exact: Annotated[
        StringTemplate,
        Field(
            description='Step header for exact-mode steps with n_of_m tracking. Template with {{step_n}} and {{step_total}} placeholders.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsStepHeaderExact',
        ),
    ]
    step_header_judgment: Annotated[
        StringTemplate,
        Field(
            description='Step header for judgment-mode steps with n_of_m tracking. Template with {{step_n}} and {{step_total}} placeholders.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsStepHeaderJudgment',
        ),
    ]
    step_header_exact_n_only: Annotated[
        StringTemplate,
        Field(
            description='Step header for exact-mode steps with n_only tracking. Template with {{step_n}} placeholder. No total shown.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsStepHeaderExactNOnly',
        ),
    ]
    step_header_judgment_n_only: Annotated[
        StringTemplate,
        Field(
            description='Step header for judgment-mode steps with n_only tracking. Template with {{step_n}} placeholder. No total shown.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsStepHeaderJudgmentNOnly',
        ),
    ]
    exact_vs_judgment_body_prefix_exact: Annotated[
        StringText,
        Field(
            description="Body prefix for exact-mode steps when marker_placement is 'body_prefix'. Short directive text preceding the step body.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.",
            title='InstructionsExactVsJudgmentBodyPrefixExact',
        ),
    ]
    exact_vs_judgment_body_prefix_judgment: Annotated[
        StringText,
        Field(
            description="Body prefix for judgment-mode steps when marker_placement is 'body_prefix'. Short directive text preceding the step body.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.",
            title='InstructionsExactVsJudgmentBodyPrefixJudgment',
        ),
    ]
    signal_at_mode_change_to_exact: Annotated[
        StringProse,
        Field(
            description='Transition signal when switching from judgment to exact mode. Rendered between consecutive steps when modes change. Visibility controlled by instructions_signal_at_mode_change_visible.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='InstructionsSignalAtModeChangeToExact',
        ),
    ]
    signal_at_mode_change_to_judgment: Annotated[
        StringProse,
        Field(
            description='Transition signal when switching from exact to judgment mode. Rendered between consecutive steps when modes change. Visibility controlled by instructions_signal_at_mode_change_visible.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='InstructionsSignalAtModeChangeToJudgment',
        ),
    ]
    step_done_when_suffix: Annotated[
        StringTemplate,
        Field(
            description='Completion condition suffix appended to step body. Template with {{completion_condition}} placeholder. Visibility controlled by instructions_step_done_when_suffix_visible.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsStepDoneWhenSuffix',
        ),
    ]
    cross_step_dependency_phrases: Annotated[
        StringTemplate,
        Field(
            description='Dependency phrase indicating which earlier steps a step builds on. Template with {{dependency_steps}} placeholder. Visibility controlled by instructions_cross_step_dependency_phrases_visible.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsCrossStepDependencyPhrases',
        ),
    ]
    halfway_point_reminder: Annotated[
        StringTemplate,
        Field(
            description='Progress reminder at the midpoint. Template with {{midpoint}}, {{midpoint_next}}, and {{step_total}} placeholders. Visibility controlled by instructions_halfway_point_reminder_visible.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsHalfwayPointReminder',
        ),
    ]
    section_closer_guardrail: Annotated[
        StringTemplate,
        Field(
            description='Section closer reinforcing completeness. Template with {{step_count}} placeholder. States that the listed steps are the complete task.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsSectionCloserGuardrail',
        ),
    ]
    section_closer_exact_vs_judgment_recap: Annotated[
        StringTemplate,
        Field(
            description='Mode recap in the section closer. Template with {{mode_recap_text}} placeholder. Summarizes which steps were exact and which judgment.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='InstructionsSectionCloserExactVsJudgmentRecap',
        ),
    ]
    exact_vs_judgment_explanation_mixed: Annotated[
        StringProse,
        Field(
            description="Explanation of the exact/judgment distinction when both modes are present. Rendered when visibility is 'auto' and modes are mixed.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.",
            title='InstructionsExactVsJudgmentExplanationMixed',
        ),
    ]
    exact_vs_judgment_explanation_uniform_exact: Annotated[
        StringProse,
        Field(
            description="Explanation when all steps are exact mode. Rendered when visibility is 'always' and all steps share the same mode.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.",
            title='InstructionsExactVsJudgmentExplanationUniformExact',
        ),
    ]
    exact_vs_judgment_explanation_uniform_judgment: Annotated[
        StringProse,
        Field(
            description="Explanation when all steps are judgment mode. Rendered when visibility is 'always' and all steps share the same mode.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.",
            title='InstructionsExactVsJudgmentExplanationUniformJudgment',
        ),
    ]
    heading_variant: Annotated[
        InstructionsHeadingVariant,
        Field(
            description='Variant alternatives for the instructions section heading. Keys match enum/heading_variant_key values. Structure selects one.',
            title='InstructionsHeadingVariant',
        ),
    ]


class ExamplesContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for examples. Plain text, no placeholders.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='ExamplesHeading',
        ),
    ]
    section_preamble: Annotated[
        StringProse,
        Field(
            description='Preamble explaining the example format. Describes the GOOD/BAD/WHY pattern and how to learn principles from examples. Position: after heading, before first group.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ExamplesSectionPreamble',
        ),
    ]
    group_framing_sentence: Annotated[
        StringTemplate,
        Field(
            description='Framing sentence between group heading and entries. Template with {{example_group_name}} placeholder. Visibility controlled by examples_group_framing_sentence_visible.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='ExamplesGroupFramingSentence',
        ),
    ]
    entry_heading: Annotated[
        StringTemplate,
        Field(
            description='Template for rendering individual example entry headings. Contains {{example_heading}} placeholder. Display format controlled by examples_entry_heading_format in display.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='ExamplesEntryHeading',
        ),
    ]


class ConstraintsSectionPreambleVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    standalone: Annotated[
        StringProse,
        Field(
            description='Preamble variant that frames constraints as a standalone section. No references to other sections. Used when constraints should be interpreted independently.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ConstraintsSectionPreambleVariantStandalone',
        ),
    ]
    references_instructions: Annotated[
        StringProse,
        Field(
            description='Preamble variant that frames constraints relative to the instructions section. Establishes that constraints modify or restrict how instructions are carried out.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ConstraintsSectionPreambleVariantReferencesInstructions',
        ),
    ]
    references_critical_rules: Annotated[
        StringProse,
        Field(
            description='Preamble variant that frames constraints relative to critical rules. Establishes constraints as a secondary enforcement tier below critical rules.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ConstraintsSectionPreambleVariantReferencesCriticalRules',
        ),
    ]


class ConstraintsClosingComplianceReminderVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evaluation_warning: Annotated[
        StringTemplate,
        Field(
            description='Closing reminder variant that frames compliance as tied to evaluation. Contains {{constraint_count}} placeholder. Warns that constraint violations will be detected during assessment.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='ConstraintsClosingComplianceReminderVariantEvaluationWarning',
        ),
    ]
    simultaneity: Annotated[
        StringTemplate,
        Field(
            description='Closing reminder variant emphasizing simultaneous application. Contains {{constraint_count}} placeholder. Stresses that all constraints must be satisfied concurrently, not selectively.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='ConstraintsClosingComplianceReminderVariantSimultaneity',
        ),
    ]


class ConstraintsNoInferredConstraintsVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    light: Annotated[
        StringProse,
        Field(
            description='Light variant of the no-inferred-constraints warning. A brief reminder that only listed constraints apply, without strong emphasis or repetition.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ConstraintsNoInferredConstraintsVariantLight',
        ),
    ]
    explicit: Annotated[
        StringTemplate,
        Field(
            description='Explicit variant of the no-inferred-constraints warning. Contains {{constraint_count}} placeholder. Strongly worded, names the exact count, and forbids inventing additional constraints.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='ConstraintsNoInferredConstraintsVariantExplicit',
        ),
    ]


class ConstraintsContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for constraints. Plain text, no placeholders. Rendered at the configured heading level.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='ConstraintsHeading',
        ),
    ]
    constraints_are_not_steps: Annotated[
        StringProse,
        Field(
            description='Prose clarifying that constraints are not sequential steps. Prevents the model from treating a numbered or bulleted constraint list as a procedure to execute in order.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ConstraintsAreNotSteps',
        ),
    ]
    constraint_count_heading: Annotated[
        StringTemplate,
        Field(
            description='Template for the constraint count heading. Contains {{constraint_count}} placeholder replaced at render time with the actual number of constraints.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='ConstraintsConstraintCountHeading',
        ),
    ]
    hierarchy_tier_comparison: Annotated[
        StringProse,
        Field(
            description='Prose explaining how constraints relate to critical rules and instructions in the enforcement hierarchy. Establishes relative authority of constraints vs other tiers.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ConstraintsHierarchyTierComparison',
        ),
    ]
    hierarchy_three_tier_explanation: Annotated[
        StringProse,
        Field(
            description='Prose explaining the three-tier enforcement hierarchy (critical rules, constraints, instructions) and how each tier relates to the others. Provides context for constraint authority level.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ConstraintsHierarchyThreeTierExplanation',
        ),
    ]
    section_preamble_variant: Annotated[
        ConstraintsSectionPreambleVariant,
        Field(
            description='Variant alternatives for the constraints section preamble. Keys match enum/section_preamble_variant_key values. Structure selects one.',
            title='ConstraintsSectionPreambleVariant',
        ),
    ]
    closing_compliance_reminder_variant: Annotated[
        ConstraintsClosingComplianceReminderVariant,
        Field(
            description='Variant alternatives for the closing compliance reminder. Keys match enum/closing_compliance_variant_key values. Structure selects one.',
            title='ConstraintsClosingComplianceReminderVariant',
        ),
    ]
    no_inferred_constraints_variant: Annotated[
        ConstraintsNoInferredConstraintsVariant,
        Field(
            description='Variant alternatives for the no-inferred-constraints warning. Keys match enum/no_inferred_constraints_variant_key values. Structure selects one.',
            title='ConstraintsNoInferredConstraintsVariant',
        ),
    ]


class AntiPatternsContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for anti-patterns. Plain text, no placeholders. Rendered at the configured heading level.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='AntiPatternsHeading',
        ),
    ]
    section_preamble: Annotated[
        StringProse,
        Field(
            description='Preamble prose for the anti-patterns section. Establishes what anti-patterns represent and how the model should interpret and avoid them during task execution.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='AntiPatternsSectionPreamble',
        ),
    ]
    constraints_vs_anti_patterns_distinction: Annotated[
        StringProse,
        Field(
            description='Prose explaining the distinction between constraints and anti-patterns. Constraints are mandatory rules; anti-patterns are behavioral pitfalls to recognize and avoid.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='AntiPatternsConstraintsVsAntiPatternsDistinction',
        ),
    ]


class SuccessCriteriaDefinitionFramingVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    declarative_assertion: Annotated[
        StringTemplate,
        Field(
            description='Definition framing that states the success definition directly. Contains {{DEFINITION}} placeholder replaced with the authored definition text.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='SuccessCriteriaDefinitionFramingVariantDeclarativeAssertion',
        ),
    ]
    conditional_gate: Annotated[
        StringTemplate,
        Field(
            description='Definition framing as an if-and-only-if condition. Contains {{DEFINITION}} placeholder. Frames success as a gate that must be passed for task completion.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='SuccessCriteriaDefinitionFramingVariantConditionalGate',
        ),
    ]
    completion_identity: Annotated[
        StringTemplate,
        Field(
            description='Definition framing as agent self-recognition of success. Contains {{DEFINITION}} placeholder. Frames success in terms of what the agent will recognize when it has succeeded.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='SuccessCriteriaDefinitionFramingVariantCompletionIdentity',
        ),
    ]


class SuccessCriteriaEvidenceFramingVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    properties: Annotated[
        StringProse,
        Field(
            description='Evidence introduction framing evidence items as properties of successful output. Objective, output-focused language.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='SuccessCriteriaEvidenceFramingVariantProperties',
        ),
    ]
    verification_checklist: Annotated[
        StringProse,
        Field(
            description='Evidence introduction framing evidence items as a verification checklist. Action-oriented, instructs the model to verify each item before declaring completion.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='SuccessCriteriaEvidenceFramingVariantVerificationChecklist',
        ),
    ]
    quality_signals: Annotated[
        StringProse,
        Field(
            description='Evidence introduction framing evidence items as truth conditions. The model knows it has succeeded when all conditions are true.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='SuccessCriteriaEvidenceFramingVariantQualitySignals',
        ),
    ]


class SuccessCriteriaDefinitionToEvidenceTransitionVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goal_then_criteria: Annotated[
        StringText,
        Field(
            description='Transition phrase using goal-oriented bridge. Connects the definition statement to the evidence list by framing evidence as what meeting the goal means.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='SuccessCriteriaDefinitionToEvidenceTransitionVariantGoalThenCriteria',
        ),
    ]
    proof: Annotated[
        StringText,
        Field(
            description='Transition phrase using proof-oriented bridge. Connects the definition statement to the evidence list by framing evidence as proof of success.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='SuccessCriteriaDefinitionToEvidenceTransitionVariantProof',
        ),
    ]
    dual_presentation: Annotated[
        StringText,
        Field(
            description='Transition phrase using confirmation-oriented bridge. Connects the definition statement to the evidence list by framing evidence as confirmation checks.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='SuccessCriteriaDefinitionToEvidenceTransitionVariantDualPresentation',
        ),
    ]


class SuccessCriteriaContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for success criteria. Plain text, no placeholders. Rendered at the configured heading level.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='SuccessCriteriaHeading',
        ),
    ]
    verification_guidance_suffix: Annotated[
        StringProse,
        Field(
            description='Suffix text reminding the model that some criteria are mechanically verifiable while others require judgment. Appended after evidence items when visibility is enabled.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='SuccessCriteriaVerificationGuidanceSuffix',
        ),
    ]
    success_failure_independence_statement: Annotated[
        StringProse,
        Field(
            description='Statement clarifying that success criteria define quality while failure criteria define breakage, and that these are independent evaluations not inverses of each other.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='SuccessCriteriaSuccessFailureIndependenceStatement',
        ),
    ]
    multi_criteria_transition: Annotated[
        StringText,
        Field(
            description='Transitional text between multiple success criteria blocks. Used when criteria count exceeds one to introduce subsequent criteria after the first.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='SuccessCriteriaMultiCriteriaTransition',
        ),
    ]
    definition_framing_variant: Annotated[
        SuccessCriteriaDefinitionFramingVariant,
        Field(
            description='Variant alternatives for how success definitions render. Keys match enum/definition_framing_variant_key values. Structure selects one.',
            title='SuccessCriteriaDefinitionFramingVariant',
        ),
    ]
    evidence_framing_variant: Annotated[
        SuccessCriteriaEvidenceFramingVariant,
        Field(
            description='Variant alternatives for how the evidence list is introduced. Keys match enum/evidence_framing_variant_key values. Structure selects one.',
            title='SuccessCriteriaEvidenceFramingVariant',
        ),
    ]
    definition_to_evidence_transition_variant: Annotated[
        SuccessCriteriaDefinitionToEvidenceTransitionVariant,
        Field(
            description='Variant alternatives for the transition between definition and evidence. Keys match enum/evidence_transition_variant_key values. Structure selects one.',
            title='SuccessCriteriaDefinitionToEvidenceTransitionVariant',
        ),
    ]


class FailureCriteriaAbortStancePreambleVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    obligation: Annotated[
        StringProse,
        Field(
            description='Abort stance preamble using obligation framing. Frames stopping as a duty — the model MUST stop when failure is detected. Producing output after detection is worse than no output.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='FailureCriteriaAbortStancePreambleVariantObligation',
        ),
    ]
    permission: Annotated[
        StringProse,
        Field(
            description='Abort stance preamble using permission framing. Frames stopping as the correct action — not every task can be completed, and forcing output past failure conditions violates quality standards.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='FailureCriteriaAbortStancePreambleVariantPermission',
        ),
    ]


class FailureCriteriaAbortStanceDefinitionLabelVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    obligation: Annotated[
        StringText,
        Field(
            description='Definition label for obligation-framed failure modes. Uses halt condition language consistent with the obligation preamble.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FailureCriteriaAbortStanceDefinitionLabelVariantObligation',
        ),
    ]
    permission: Annotated[
        StringText,
        Field(
            description='Definition label for permission-framed failure modes. Uses impossibility language consistent with the permission preamble.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FailureCriteriaAbortStanceDefinitionLabelVariantPermission',
        ),
    ]


class FailureCriteriaAbortStanceVariantContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    preamble: Annotated[
        FailureCriteriaAbortStancePreambleVariant,
        Field(
            description='Variant alternatives for the abort stance preamble. Keys match enum/abort_stance_variant_key values. Structure selects one.',
            title='FailureCriteriaAbortStancePreambleVariant',
        ),
    ]
    definition_label: Annotated[
        FailureCriteriaAbortStanceDefinitionLabelVariant,
        Field(
            description='Variant alternatives for the failure mode definition label. Keys match enum/abort_stance_variant_key values. Structure selects one.',
            title='FailureCriteriaAbortStanceDefinitionLabelVariant',
        ),
    ]


class FailureCriteriaContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for failure criteria. Plain text, no placeholders. Rendered at the configured heading level. Typically uses "Abort Conditions" rather than "Failure Criteria."\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='FailureCriteriaHeading',
        ),
    ]
    any_one_triggers_abort: Annotated[
        StringProse,
        Field(
            description='Prose establishing that any single failure mode is sufficient to trigger abort. Prevents the model from waiting for multiple failure signals before stopping.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='FailureCriteriaAnyOneTriggersAbort',
        ),
    ]
    evidence_preamble: Annotated[
        StringProse,
        Field(
            description='Prose introducing the evidence list for each failure mode. Establishes that any single signal is sufficient to indicate the failure mode is active.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='FailureCriteriaEvidencePreamble',
        ),
    ]
    cite_definition_and_evidence_postscript: Annotated[
        StringProse,
        Field(
            description='Postscript instructing the model to cite both the failure definition and evidence when reporting failure. Connects the definition/evidence hierarchy to the return_format reporting structure.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='FailureCriteriaCiteDefinitionAndEvidencePostscript',
        ),
    ]
    check_before_and_during: Annotated[
        StringProse,
        Field(
            description='Generic temporal instruction about checking failure conditions before starting work and monitoring throughout execution.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='FailureCriteriaCheckBeforeAndDuring',
        ),
    ]
    abort_stance_variant: Annotated[
        FailureCriteriaAbortStanceVariantContent,
        Field(
            description='Shared variant content for failure criteria abort stance. Contains two content families (preamble, definition_label) that both switch together based on the abort_stance_variant selector in structure. Each family is a simplegroup with one field per variant key.',
            title='FailureCriteriaAbortStanceVariantContent',
        ),
    ]


class OutputDirectoryLocationVariant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    standard: Annotated[
        StringTemplate,
        Field(
            description='Directory location variant that states the output directory path directly. Contains {{OUTPUT_DIRECTORY}} placeholder.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='OutputDirectoryLocationVariantStandard',
        ),
    ]
    with_boundary: Annotated[
        StringTemplate,
        Field(
            description='Directory location variant that states the output directory and adds an explicit boundary constraint. Contains {{OUTPUT_DIRECTORY}} placeholder. All files must be within this directory or its subdirectories.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='OutputDirectoryLocationVariantWithBoundary',
        ),
    ]


class OutputContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for the output section. Plain text, no placeholders. Rendered at the configured heading level.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='OutputHeading',
        ),
    ]
    output_description: Annotated[
        StringTemplate,
        Field(
            description='Template describing what the agent produces. Contains {{DESCRIPTION}} placeholder replaced with the authored output description from the agent definition.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='OutputOutputDescription',
        ),
    ]
    format_declaration: Annotated[
        StringTemplate,
        Field(
            description='Template declaring the output format. Contains {{FORMAT}} placeholder replaced with the configured output format value.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='OutputFormatDeclaration',
        ),
    ]
    schema_embedded_preamble: Annotated[
        StringProse,
        Field(
            description='Preamble text rendered when schema_embed is true. Introduces the inline schema and instructs the model that every record must validate against it.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='OutputSchemaEmbeddedPreamble',
        ),
    ]
    schema_reference: Annotated[
        StringTemplate,
        Field(
            description='Template for the schema path reference when schema_embed is false. Contains {{SCHEMA_PATH}} placeholder. Instructs the model to read the schema at the given path and conform output to it.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='OutputSchemaReference',
        ),
    ]
    directory_location_variant: Annotated[
        OutputDirectoryLocationVariant,
        Field(
            description='Variant alternatives for the output directory location declaration. Keys match enum/directory_location_variant_key values. Structure selects one.',
            title='OutputDirectoryLocationVariant',
        ),
    ]


class WritingOutputContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for the output mechanics section. Plain text, no placeholders. Rendered at the configured heading level.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='WritingOutputHeading',
        ),
    ]
    transition_preamble: Annotated[
        StringProse,
        Field(
            description='Transition sentence connecting from instructions to the output mechanics section. Bridges the what-to-do with the how-to-deliver.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='WritingOutputTransitionPreamble',
        ),
    ]
    tool_mandate: Annotated[
        StringProse,
        Field(
            description='Prose establishing that output flows through one channel only. The agent does not write files directly or choose alternative tools. Enforces single-tool exclusivity.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='WritingOutputToolMandate',
        ),
    ]
    tool_identity_label: Annotated[
        StringTemplate,
        Field(
            description='Template identifying the output tool. Contains {{TOOL_NAME}} placeholder replaced with the configured tool name. Rendered as a label the agent uses to identify its output channel.\nProse string containing at least one {{placeholder}} interpolation marker. The renderer substitutes marker contents with data field values at composition time. Used for content.toml template blobs like headings, declarations, and labels that embed agent-specific data in prose.',
            title='WritingOutputToolIdentityLabel',
        ),
    ]
    invocation_preamble: Annotated[
        StringProse,
        Field(
            description='Preamble introducing the invocation template. Instructs the agent to copy the template exactly, substituting only the marked placeholders.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='WritingOutputInvocationPreamble',
        ),
    ]
    heredoc_explanation: Annotated[
        StringProse,
        Field(
            description='Explanation of heredoc syntax for passing multi-line JSON to the output tool. Clarifies that EOF markers delimit the content block.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='WritingOutputHeredocExplanation',
        ),
    ]


class ReturnFormatContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Annotated[
        StringText,
        Field(
            description='Section heading for the return protocol section. Plain text, no placeholders. Rendered at the configured heading level.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='ReturnFormatHeading',
        ),
    ]
    files_vs_status_explanation_preamble: Annotated[
        StringProse,
        Field(
            description='Prose explaining the two-channel model. Work products go to files, the return goes to the dispatcher as a brief status signal — not the deliverable.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatFilesVsStatusExplanationPreamble',
        ),
    ]
    token_must_be_first_word_preamble: Annotated[
        StringProse,
        Field(
            description='Prose establishing that the return must begin with a protocol token. The dispatch layer parses this token programmatically. It must not be paraphrased or embedded in prose.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatTokenMustBeFirstWordPreamble',
        ),
    ]
    token_must_be_first_word_tokens_three: Annotated[
        StringProse,
        Field(
            description='Prose listing the three terminal states: SUCCESS, FAILURE, or ABORT. Used when the agent definition includes ABORT as a valid return token.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatTokenMustBeFirstWordTokensThree',
        ),
    ]
    token_must_be_first_word_tokens_two: Annotated[
        StringProse,
        Field(
            description='Prose listing the two terminal states: SUCCESS or FAILURE. Used when the agent definition does not include ABORT as a valid return token.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatTokenMustBeFirstWordTokensTwo',
        ),
    ]
    report_completion_label: Annotated[
        StringText,
        Field(
            description='Label text introducing the completion report format. Plain text, no placeholders. Precedes the structured return template.\nNatural language prose — must contain at least one whitespace character. Mutually exclusive with all identifier types. Used for descriptions, instructions, error messages, and display labels. Not a path.',
            title='ReturnFormatReportCompletionLabel',
        ),
    ]
    report_all_metrics_postscript: Annotated[
        StringProse,
        Field(
            description='Postscript reminding the agent to report all metrics specified for its return state. The dispatcher and downstream processes depend on these values being present.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatReportAllMetricsPostscript',
        ),
    ]
    abort_vs_failure_distinction_preamble: Annotated[
        StringProse,
        Field(
            description='Prose distinguishing ABORT from FAILURE. ABORT means the work should not be attempted. It is not failure — it is a responsible decision to stop before producing bad output.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatAbortVsFailureDistinctionPreamble',
        ),
    ]
    honest_failure_over_dubious_success_preamble: Annotated[
        StringProse,
        Field(
            description='Prose granting explicit permission to return clean FAILURE. An honest FAILURE is better than a dubious SUCCESS. A clean FAILURE with a clear reason is more valuable than compromised output.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatHonestFailureOverDubiousSuccessPreamble',
        ),
    ]
    track_metrics_as_you_work_postscript: Annotated[
        StringProse,
        Field(
            description='Postscript establishing retroactive orientation. Return requirements imply tracking requirements — if you must report a count, maintain it as you work; if you must report a path, know it before you write.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatTrackMetricsAsYouWorkPostscript',
        ),
    ]
    track_metrics_as_you_work_antidrift: Annotated[
        StringProse,
        Field(
            description='Anti-drift prose establishing that the dispatcher is waiting for the return signal. When a terminal state is reached, report it immediately. Do not continue work after reaching a terminal state.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatTrackMetricsAsYouWorkAntidrift',
        ),
    ]
    do_not_fabricate_metrics_postscript: Annotated[
        StringProse,
        Field(
            description='Postscript requiring the agent to report actual metrics from execution. Do not fabricate values to match the expected format.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatDoNotFabricateMetricsPostscript',
        ),
    ]
    failure_cross_reference_preamble: Annotated[
        StringProse,
        Field(
            description='Cross-reference prose connecting the return protocol to the failure criteria section. Clarifies that failure conditions are defined elsewhere and this section covers how to report failure.\nSubstantive prose text that forms complete sentences. Starts with a capital letter, contains at least three whitespace characters, ends with sentence punctuation. Structural constraints prevent non-prose abuse, so path exclusions are not needed. Used for descriptions, instructions, and multi-sentence text that may reference file paths.',
            title='ReturnFormatFailureCrossReferencePreamble',
        ),
    ]


class AgentOutputContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identity: Annotated[
        IdentityContent,
        Field(
            description='Content prose for the identity section. Heading, declaration templates, role labels, expertise label, and closing reminder.',
            title='IdentityContent',
        ),
    ]
    security_boundary: Annotated[
        SecurityBoundaryContent,
        Field(
            description='Content prose for the security boundary section. Filesystem map intro, section closing, entry templates, and framing variant sub-tables.',
            title='SecurityBoundaryContent',
        ),
    ]
    critical_rules: Annotated[
        CriticalRulesContent,
        Field(
            description='Content prose for the critical rules section. Heading, authority preamble, and one prose template per rule.',
            title='CriticalRulesContent',
        ),
    ]
    instructions: Annotated[
        InstructionsContent,
        Field(
            description='Content prose for the instructions section. Preamble components, step header templates, mode markers, dependency phrases, closer text, and heading variant sub-table.',
            title='InstructionsContent',
        ),
    ]
    examples: Annotated[
        ExamplesContent,
        Field(
            description='Content prose for the examples section. Heading, preamble, group framing sentence, and entry heading template.',
            title='ExamplesContent',
        ),
    ]
    constraints: Annotated[
        ConstraintsContent,
        Field(
            description='Content prose for the constraints section. Heading, plain prose fields, and variant sub-tables for preamble, closing reminder, and no-inferred-constraints warning.',
            title='ConstraintsContent',
        ),
    ]
    anti_patterns: Annotated[
        AntiPatternsContent,
        Field(
            description='Content prose for the anti-patterns section. Heading, preamble, and distinction prose.',
            title='AntiPatternsContent',
        ),
    ]
    success_criteria: Annotated[
        SuccessCriteriaContent,
        Field(
            description='Content prose for the success criteria section. Heading, plain prose, and variant sub-tables for definition framing, evidence framing, and definition-to-evidence transition.',
            title='SuccessCriteriaContent',
        ),
    ]
    failure_criteria: Annotated[
        FailureCriteriaContent,
        Field(
            description='Content prose for the failure criteria section. Heading, plain prose, and abort stance variant sub-tables for preamble and definition label.',
            title='FailureCriteriaContent',
        ),
    ]
    output: Annotated[
        OutputContent,
        Field(
            description='Content prose for the output section. Heading, description and format templates, schema prose, and directory location variant sub-table.',
            title='OutputContent',
        ),
    ]
    writing_output: Annotated[
        WritingOutputContent,
        Field(
            description='Content prose for the writing output section. Heading, transition preamble, tool mandate, identity label, invocation preamble, and heredoc explanation.',
            title='WritingOutputContent',
        ),
    ]
    return_format: Annotated[
        ReturnFormatContent,
        Field(
            description='Content prose for the return format section. Heading, protocol components, metrics obligations, abort/failure distinction, and tracking requirements.',
            title='ReturnFormatContent',
        ),
    ]
