# generated by datamodel-codegen:
#   filename:  agent-output-structure.schema.json
#   timestamp: 2026-03-24T13:05:30+00:00

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class IdentityFieldOrdering(Enum):
    identity_first = 'identity_first'
    responsibility_first = 'responsibility_first'


class SecurityBoundaryFramingVariant(Enum):
    territory = 'territory'
    environmental = 'environmental'
    cage = 'cage'


class CriticalRulesRulePresentation(Enum):
    single_sentence = 'single_sentence'
    heading_plus_body = 'heading_plus_body'


class CriticalRulesInternalHierarchy(Enum):
    flat = 'flat'
    universal_then_output_tool = 'universal_then_output_tool'


class InstructionsHeadingVariant(Enum):
    default = 'default'
    procedure = 'procedure'
    steps_with_count = 'steps_with_count'


class InstructionsExactVsJudgmentMarkerPlacement(Enum):
    header_fused = 'header_fused'
    body_prefix = 'body_prefix'
    visual_formatting = 'visual_formatting'


class InstructionsStepIndexTracking(Enum):
    n_only = 'n_only'
    n_of_m = 'n_of_m'


class InstructionsStructuralComplexityOverride(Enum):
    auto = 'auto'
    lightweight = 'lightweight'
    standard = 'standard'
    heavy = 'heavy'


class ConstraintsSectionPreambleVariant(Enum):
    standalone = 'standalone'
    references_instructions = 'references_instructions'
    references_critical_rules = 'references_critical_rules'


class ConstraintsClosingComplianceReminderVariant(Enum):
    evaluation_warning = 'evaluation_warning'
    simultaneity = 'simultaneity'


class ConstraintsNoInferredConstraintsVariant(Enum):
    light = 'light'
    explicit = 'explicit'


class SuccessCriteriaDefinitionFramingVariant(Enum):
    declarative_assertion = 'declarative_assertion'
    conditional_gate = 'conditional_gate'
    completion_identity = 'completion_identity'


class SuccessCriteriaEvidenceFramingVariant(Enum):
    properties = 'properties'
    verification_checklist = 'verification_checklist'
    quality_signals = 'quality_signals'


class SuccessCriteriaDefinitionToEvidenceTransitionVariant(Enum):
    goal_then_criteria = 'goal_then_criteria'
    proof = 'proof'
    dual_presentation = 'dual_presentation'


class SuccessCriteriaEvidenceTypeHandling(Enum):
    graduated_language = 'graduated_language'
    undifferentiated = 'undifferentiated'


class SuccessCriteriaOutputVsAgentVoice(Enum):
    output_centric = 'output_centric'
    agent_centric = 'agent_centric'


class SuccessCriteriaMultiCriteriaRelationship(Enum):
    independent_blocks = 'independent_blocks'
    numbered_dimensions = 'numbered_dimensions'


class FailureCriteriaAbortStanceVariant(Enum):
    obligation = 'obligation'
    permission = 'permission'


class OutputDirectoryLocationVariant(Enum):
    standard = 'standard'
    with_boundary = 'with_boundary'


class Boolean(RootModel[bool]):
    root: Annotated[bool, Field(description='True or false value', title='Boolean')]


class VisibilityMode(Enum):
    auto = 'auto'
    always = 'always'
    never = 'never'


class Integer(RootModel[int]):
    root: Annotated[int, Field(description='Whole number value', title='Integer')]


class IdentityStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_ordering: Annotated[
        IdentityFieldOrdering,
        Field(
            description="Structural variant for identity section field sequence. Controls whether the section leads with role identity and declaration (identity_first) or with scope and responsibility (responsibility_first).\nStructural variant for identity section field sequence. 'identity_first' leads with role identity and declaration. 'responsibility_first' leads with scope and responsibility.",
            title='IdentityFieldOrdering',
        ),
    ]
    fuse_declaration_and_role_description: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to merge the identity declaration and role description into a single paragraph. When false, declaration and role description render as separate blocks. When true, they fuse into one flowing paragraph.\nTrue or false value',
            title='IdentityFuseDeclarationAndRoleDescription',
        ),
    ]
    expertise_is_strictly_limited_postscript_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the expertise limitation postscript after the expertise list. When true, a reinforcement statement constraining expertise to the listed areas appears after the list. When false, the expertise list renders without a closing constraint.\nTrue or false value',
            title='IdentityExpertisePostscriptVisible',
        ),
    ]
    closing_identity_reminder_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description="Whether to render a closing identity reminder at the end of the identity section. When true, a reinforcement sentence restating the agent's role identity appears as the section closer. Off by default — identity is established at the top and does not need restating unless experiments show drift.\nTrue or false value",
            title='IdentityClosingReminderVisible',
        ),
    ]
    bold_contrast_phrase_from_role_description_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to extract and bold a contrast phrase from the role description. When true, the renderer scans role_description for a contrastive clause (e.g., "not a debugger, not a reviewer") and renders it with bold emphasis. Off by default — most role descriptions do not contain contrast phrases.\nTrue or false value',
            title='IdentityBoldContrastVisible',
        ),
    ]


class SecurityBoundaryStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fuse_workspace_path_and_resolver: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to merge the workspace path declaration with the path resolution instruction in a single sentence. When true, renders as one flowing statement. When false, workspace path and resolution instruction render as separate lines.\nTrue or false value',
            title='SecurityBoundaryFuseWorkspacePathAndResolver',
        ),
    ]
    filesystem_map_intro_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render an introductory line before the filesystem display entries. Visibility may also be governed by filesystem_map_intro_visibility_threshold in display — the threshold overrides this toggle when entry count is below it.\nTrue or false value',
            title='SecurityBoundaryFilesystemMapIntroVisible',
        ),
    ]
    section_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render a preamble between the section heading and the display entries. The preamble text is selected by framing_variant in content.\nTrue or false value',
            title='SecurityBoundarySectionPreambleVisible',
        ),
    ]
    section_closing_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render a closing statement after the display entries. Off by default — the entries are self-contained and hooks enforce access regardless of prose.\nTrue or false value',
            title='SecurityBoundarySectionClosingVisible',
        ),
    ]
    tool_names_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to show tool names alongside paths in display entries. When false, entries show paths only. Hooks enforce tool access regardless — this controls what the agent sees, not what it can do.\nTrue or false value',
            title='SecurityBoundaryToolNamesVisible',
        ),
    ]
    framing_variant: Annotated[
        SecurityBoundaryFramingVariant,
        Field(
            description="Posture for the security boundary section. Selects which content variant renders for heading, workspace_path_declaration, and section_preamble simultaneously. All three content families use the same variant key.\nPosture for security boundary presentation. 'territory' frames the workspace as the agent's domain. 'environmental' frames it as the operating context. 'cage' frames it as a confinement boundary. Governs heading, workspace path declaration, and section preamble.",
            title='SecurityBoundaryFramingVariant',
        ),
    ]


class CriticalRulesStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    authority_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the authority preamble establishing that critical rules override all other instructions. Sets the stakes before individual rules are listed.\nTrue or false value',
            title='CriticalRulesAuthorityPreambleVisible',
        ),
    ]
    rule_count_awareness_prelude_visible: Annotated[
        VisibilityMode,
        Field(
            description="Whether to render the rule count awareness prelude. 'auto' renders when rule count exceeds the auto_threshold. 'always' forces it on. 'never' suppresses it. The prelude tells the agent how many rules to expect.\nTri-state visibility control for optional prose fragments. 'auto' delegates to a threshold or data condition — the renderer decides. 'always' forces the fragment to render regardless of conditions. 'never' suppresses the fragment regardless of conditions.",
            title='CriticalRulesRuleCountAwarenessPreludeVisible',
        ),
    ]
    rule_count_awareness_prelude_auto_threshold: Annotated[
        Integer,
        Field(
            default_factory=lambda: Integer(5),
            description="Rule count threshold for the auto mode of rule_count_awareness_prelude_visible. When rule count exceeds this threshold and visibility is 'auto', the prelude renders.\nWhole number value",
            title='CriticalRulesRuleCountAwarenessPreludeAutoThreshold',
        ),
    ]
    workspace_confinement_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the workspace confinement rule. Declares that nothing outside the workspace path exists. Hooks enforce this regardless — the toggle tests whether the prose helps.\nTrue or false value',
            title='CriticalRulesWorkspaceConfinementVisible',
        ),
    ]
    fail_fast_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the fail-fast rule. Instructs the agent to return FAILURE immediately on error rather than attempting recovery.\nTrue or false value',
            title='CriticalRulesFailFastVisible',
        ),
    ]
    input_is_your_only_source_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the input-only-source rule. Prohibits the agent from supplementing input with external sources, training data, or additional materials.\nTrue or false value',
            title='CriticalRulesInputIsYourOnlySourceVisible',
        ),
    ]
    no_invention_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the no-invention rule. Requires every claim in output to trace to input. Silence is correct when data is absent.\nTrue or false value',
            title='CriticalRulesNoInventionVisible',
        ),
    ]
    output_tool_exclusivity_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the output tool exclusivity rule. Declares that the named tool is the only output mechanism. Conditional on has_output_tool — data gate suppresses when no tool exists.\nTrue or false value',
            title='CriticalRulesOutputToolExclusivityVisible',
        ),
    ]
    batch_discipline_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the batch discipline rule. Requires processing in batches of the specified size with immediate writes. Conditional on both has_output_tool and batch_size being present.\nTrue or false value',
            title='CriticalRulesBatchDisciplineVisible',
        ),
    ]
    discipline_over_helpfulness_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render the discipline-over-helpfulness rule. Reframes discipline as the helpful behavior. Off by default — experimental rule testing whether explicit reframing reduces helpfulness drift.\nTrue or false value',
            title='CriticalRulesDisciplineOverHelpfulnessVisible',
        ),
    ]
    rule_presentation: Annotated[
        CriticalRulesRulePresentation,
        Field(
            description="How individual rules render. 'single_sentence' presents each rule as a dense single sentence. 'heading_plus_body' gives each rule a bold heading with an explanatory body beneath.\nHow critical rules render. 'single_sentence' presents each rule as a single dense sentence. 'heading_plus_body' gives each rule a bold heading with an explanatory body beneath.",
            title='CriticalRulesRulePresentation',
        ),
    ]
    internal_hierarchy: Annotated[
        CriticalRulesInternalHierarchy,
        Field(
            description="Internal organization of critical rules. 'flat' renders all rules in a single list. 'universal_then_output_tool' groups into universal rules (always apply) followed by output-tool-specific rules.\nInternal organization of critical rules. 'flat' renders all rules in a single list with no grouping. 'universal_then_output_tool' groups rules into universal rules (always apply) followed by output-tool-specific rules (conditional on has_output_tool).",
            title='CriticalRulesInternalHierarchy',
        ),
    ]


class InstructionsStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading_variant: Annotated[
        InstructionsHeadingVariant,
        Field(
            description="Selects which heading variant renders for the instructions section. 'default' uses a plain heading. 'procedure' uses formal procedural language. 'steps_with_count' includes the total step count.\nInstructions section heading style. 'default' uses a plain heading. 'procedure' uses formal procedural language. 'steps_with_count' includes the total step count in the heading.",
            title='InstructionsHeadingVariant',
        ),
    ]
    exact_vs_judgment_explanation_visible: Annotated[
        VisibilityMode,
        Field(
            description="Whether to render the exact/judgment mode explanation. 'auto' renders when instruction modes are mixed (both exact and judgment steps present). 'always' forces it on. 'never' suppresses it.\nTri-state visibility control for optional prose fragments. 'auto' delegates to a threshold or data condition — the renderer decides. 'always' forces the fragment to render regardless of conditions. 'never' suppresses the fragment regardless of conditions.",
            title='InstructionsExactVsJudgmentExplanationVisible',
        ),
    ]
    exact_vs_judgment_marker_placement: Annotated[
        InstructionsExactVsJudgmentMarkerPlacement,
        Field(
            description="Where exact/judgment mode markers appear in instruction steps. 'header_fused' embeds in the step header. 'body_prefix' places as the first line of step body. 'visual_formatting' uses visual cues to distinguish modes without explicit text.\nWhere exact/judgment mode markers appear in instruction steps. 'header_fused' embeds the marker in the step header text. 'body_prefix' places the marker as the first line of the step body. 'visual_formatting' uses visual cues (e.g., bold vs italic) to distinguish modes without explicit text markers.",
            title='InstructionsExactVsJudgmentMarkerPlacement',
        ),
    ]
    signal_at_mode_change_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render a transition signal when consecutive steps switch between exact and judgment modes. Off by default — mode markers in headers are usually sufficient.\nTrue or false value',
            title='InstructionsSignalAtModeChangeVisible',
        ),
    ]
    instructions_preamble_step_count_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the step count statement in the preamble. Tells the agent how many steps to expect.\nTrue or false value',
            title='InstructionsPreambleStepCountVisible',
        ),
    ]
    instructions_preamble_no_add_skip_reorder_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the prohibition against adding, skipping, or reordering steps in the preamble.\nTrue or false value',
            title='InstructionsPreambleNoAddSkipReorderVisible',
        ),
    ]
    instructions_preamble_exact_vs_judgment_preview_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the exact/judgment mode preview in the preamble. Previews that some steps are exact (no interpretation) and some require judgment.\nTrue or false value',
            title='InstructionsPreambleExactVsJudgmentPreviewVisible',
        ),
    ]
    instructions_preamble_no_extra_operations_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the prohibition against supplementing steps with general knowledge or adding unspecified operations.\nTrue or false value',
            title='InstructionsPreambleNoExtraOperationsVisible',
        ),
    ]
    step_index_tracking: Annotated[
        InstructionsStepIndexTracking,
        Field(
            description="How step numbers render in headers. 'n_only' shows just the step number. 'n_of_m' shows step number and total.\nHow step numbers render in instruction headers. 'n_only' shows just the step number (Step 3). 'n_of_m' shows step number and total (Step 3 of 7).",
            title='InstructionsStepIndexTracking',
        ),
    ]
    step_done_when_suffix_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render a completion condition suffix after each step body. Off by default — most steps are self-evident about completion.\nTrue or false value',
            title='InstructionsStepDoneWhenSuffixVisible',
        ),
    ]
    section_closer_guardrail_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the section closer reinforcing that the listed steps are the complete task with no additions.\nTrue or false value',
            title='InstructionsSectionCloserGuardrailVisible',
        ),
    ]
    section_closer_exact_vs_judgment_recap_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render a mode recap in the section closer summarizing which steps were exact and which required judgment.\nTrue or false value',
            title='InstructionsSectionCloserExactVsJudgmentRecapVisible',
        ),
    ]
    cross_step_dependency_phrases_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description="Whether to render dependency phrases indicating which earlier steps a step's output depends on. Off by default — adds noise for simple linear workflows.\nTrue or false value",
            title='InstructionsCrossStepDependencyPhrasesVisible',
        ),
    ]
    halfway_point_reminder_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render a progress reminder at the midpoint of the step list. Off by default — only useful for long instruction sets where the agent may lose orientation.\nTrue or false value',
            title='InstructionsHalfwayPointReminderVisible',
        ),
    ]
    structural_complexity_override: Annotated[
        InstructionsStructuralComplexityOverride,
        Field(
            description="Scaffolding tier for instruction rendering. 'auto' selects from step count using activation thresholds. 'lightweight' uses minimal scaffolding. 'standard' adds preamble, markers, and closers. 'heavy' adds progress reminders, dependencies, and recaps.\nStructural complexity tier for instruction rendering. 'auto' selects tier from step count using activation thresholds. 'lightweight' uses minimal scaffolding (few steps, little overhead). 'standard' adds preamble, mode markers, and closers. 'heavy' adds progress reminders, dependency phrases, and detailed recaps.",
            title='InstructionsStructuralComplexityOverride',
        ),
    ]


class ExamplesStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    section_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the section preamble explaining how to read examples (GOOD/BAD/WHY pattern).\nTrue or false value',
            title='ExamplesSectionPreambleVisible',
        ),
    ]
    suppress_lone_group_heading: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to suppress the group heading when only one example group exists. When true, a single-group agent skips the group heading and promotes entries directly under the section heading.\nTrue or false value',
            title='ExamplesSuppressLoneGroupHeading',
        ),
    ]
    example_display_headings_override: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to override the per-group example_display_headings from data. When false, data passes through unchanged. When true, the sibling examples_example_display_headings value is used instead.\nTrue or false value',
            title='ExamplesExampleDisplayHeadingsOverride',
        ),
    ]
    examples_max_number_override: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to override the per-group examples_max_number from data. When false, data passes through unchanged. When true, the sibling examples_max_number value is used instead.\nTrue or false value',
            title='ExamplesMaxNumberOverride',
        ),
    ]
    group_framing_sentence_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render a framing sentence between the group heading and its first entry. Off by default — group headings are usually self-explanatory.\nTrue or false value',
            title='ExamplesGroupFramingSentenceVisible',
        ),
    ]
    example_display_headings: Annotated[
        Boolean | None,
        Field(
            default_factory=lambda: Boolean(True),
            description='Override value for example entry headings. Only applies when examples_example_display_headings_override is true. Controls whether individual example entries show their headings.\nTrue or false value',
            title='ExamplesExampleDisplayHeadings',
        ),
    ]
    examples_max_number: Annotated[
        Integer | None,
        Field(
            default_factory=lambda: Integer(0),
            description='Override value for maximum examples to render per group. Only applies when examples_max_number_override is true. 0 means no truncation. N > 0 caps at N entries, preserving author priority order.\nWhole number value',
            title='ExamplesMaxNumber',
        ),
    ]


class ConstraintsStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    section_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the constraints section at all. When false, the entire section is suppressed regardless of other constraint settings.\nTrue or false value',
            title='ConstraintsSectionVisible',
        ),
    ]
    max_entries_rendered: Annotated[
        Integer,
        Field(
            default_factory=lambda: Integer(0),
            description='Maximum number of constraint entries to render. Zero means render all entries without limit. Positive values cap the list, useful for token budget control when constraint counts are high.\nWhole number value',
            title='ConstraintsMaxEntriesRendered',
        ),
    ]
    section_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the preamble text before the constraint list. The preamble establishes context for how constraints should be interpreted relative to other sections.\nTrue or false value',
            title='ConstraintsSectionPreambleVisible',
        ),
    ]
    constraints_are_not_steps_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the clarification that constraints are not sequential steps. Prevents models from treating a constraint list as a procedure to follow in order.\nTrue or false value',
            title='ConstraintsAreNotStepsVisible',
        ),
    ]
    no_inferred_constraints_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render an explicit warning against inferring constraints not listed. Off by default — only needed when models tend to invent additional constraints from context.\nTrue or false value',
            title='ConstraintsNoInferredConstraintsVisible',
        ),
    ]
    closing_compliance_reminder_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render a closing reminder about constraint compliance after the constraint list. Reinforces obligation at the boundary where the model transitions to the next section.\nTrue or false value',
            title='ConstraintsClosingComplianceReminderVisible',
        ),
    ]
    constraint_count_heading_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render a heading that includes the constraint count. Makes the model aware of how many constraints exist, which can improve compliance tracking.\nTrue or false value',
            title='ConstraintsConstraintCountHeadingVisible',
        ),
    ]
    section_preamble_variant: Annotated[
        ConstraintsSectionPreambleVariant | None,
        Field(
            description="Selects which preamble variant to use for the constraints section. 'standalone' frames constraints independently. 'references_instructions' and 'references_critical_rules' frame constraints relative to other sections.\nConstraints section preamble posture. 'standalone' frames constraints as self-contained governance. 'references_instructions' connects them to the instruction steps. 'references_critical_rules' positions them relative to the critical rules tier.",
            title='ConstraintsSectionPreambleVariant',
        ),
    ] = 'standalone'
    closing_compliance_reminder_variant: Annotated[
        ConstraintsClosingComplianceReminderVariant | None,
        Field(
            description="Selects the tone of the closing compliance reminder. 'evaluation_warning' frames compliance as tied to evaluation. 'simultaneity' emphasizes that all constraints apply simultaneously.\nConstraints closing reinforcement posture. 'evaluation_warning' reminds the agent that output will be audited against each constraint. 'simultaneity' reminds the agent that all constraints apply at once.",
            title='ConstraintsClosingComplianceReminderVariant',
        ),
    ] = 'evaluation_warning'
    no_inferred_constraints_variant: Annotated[
        ConstraintsNoInferredConstraintsVariant | None,
        Field(
            description="Selects how strongly the no-inferred-constraints warning is worded. 'light' is a brief reminder. 'explicit' is a template-based warning that names the constraint count.\nHow the constraint exhaustiveness statement renders. 'light' is a brief acknowledgment. 'explicit' states the count and forbids inferring additional constraints not listed.",
            title='ConstraintsNoInferredConstraintsVariant',
        ),
    ] = 'light'


class AntiPatternsStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    section_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the anti-patterns section at all. When false, the entire section is suppressed regardless of other anti-pattern settings.\nTrue or false value',
            title='AntiPatternsSectionVisible',
        ),
    ]
    max_entries_rendered: Annotated[
        Integer,
        Field(
            default_factory=lambda: Integer(0),
            description='Maximum number of anti-pattern entries to render. Zero means render all entries without limit.\nWhole number value',
            title='AntiPatternsMaxEntriesRendered',
        ),
    ]
    section_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the preamble text before the anti-pattern list. The preamble establishes what anti-patterns are and how the model should avoid them.\nTrue or false value',
            title='AntiPatternsSectionPreambleVisible',
        ),
    ]
    constraints_vs_anti_patterns_distinction_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render text distinguishing anti-patterns from constraints. Clarifies that anti-patterns are behaviors to avoid while constraints are rules to follow.\nTrue or false value',
            title='AntiPatternsConstraintsVsAntiPatternsDistinctionVisible',
        ),
    ]


class SuccessCriteriaStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    section_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the success criteria section at all. When false, the entire section is suppressed regardless of other settings.\nTrue or false value',
            title='SuccessCriteriaSectionVisible',
        ),
    ]
    max_entries_rendered: Annotated[
        Integer,
        Field(
            default_factory=lambda: Integer(0),
            description='Maximum number of success criteria entries to render. Zero means render all entries without limit.\nWhole number value',
            title='SuccessCriteriaMaxEntriesRendered',
        ),
    ]
    definition_framing_variant: Annotated[
        SuccessCriteriaDefinitionFramingVariant,
        Field(
            description="Selects how the success definition statement renders. 'declarative_assertion' states the definition directly. 'conditional_gate' frames it as an if-and-only-if condition. 'completion_identity' frames it as agent self-recognition.\nHow success criteria definitions render. 'declarative_assertion' states the criterion directly. 'conditional_gate' frames it as a necessary condition for completion. 'completion_identity' frames it as what the agent has achieved when done.",
            title='SuccessCriteriaDefinitionFramingVariant',
        ),
    ]
    evidence_framing_variant: Annotated[
        SuccessCriteriaEvidenceFramingVariant,
        Field(
            description="Selects how the evidence list introduction renders. 'properties' frames evidence as output properties. 'verification_checklist' frames as items to verify. 'quality_signals' frames as observable truth conditions.\nHow success criteria evidence lists render. 'properties' frames evidence as output properties. 'verification_checklist' frames evidence as items to verify before declaring completion. 'quality_signals' frames evidence as observable indicators of success.",
            title='SuccessCriteriaEvidenceFramingVariant',
        ),
    ]
    definition_to_evidence_transition_variant: Annotated[
        SuccessCriteriaDefinitionToEvidenceTransitionVariant,
        Field(
            description="Selects the transitional phrase between definition and evidence. 'goal_then_criteria' uses a goal-oriented bridge. 'proof' uses a proof-oriented bridge. 'dual_presentation' uses a confirmation-oriented bridge.\nHow the transition from definition to evidence renders. 'goal_then_criteria' frames evidence as what meeting the standard means. 'proof' frames evidence as proof of the definition. 'dual_presentation' frames evidence as a confirmation check.",
            title='SuccessCriteriaDefinitionToEvidenceTransitionVariant',
        ),
    ]
    evidence_type_handling: Annotated[
        SuccessCriteriaEvidenceTypeHandling,
        Field(
            description="How evidence items render relative to their type markers. 'undifferentiated' renders all evidence items uniformly. 'graduated_language' varies language based on evidence type.\nHow evidence items are rendered relative to their type markers. 'graduated_language' adds per-item type markers distinguishing mechanical from judgment evidence. 'undifferentiated' renders all evidence items equally with no type distinction.",
            title='SuccessCriteriaEvidenceTypeHandling',
        ),
    ]
    output_vs_agent_voice: Annotated[
        SuccessCriteriaOutputVsAgentVoice,
        Field(
            description="Voice paradigm for success criteria prose. 'output_centric' describes success in terms of what the output looks like. 'agent_centric' describes success in terms of what the agent did.\nVoice paradigm for success criteria prose. 'output_centric' frames criteria in terms of what the output must be. 'agent_centric' frames criteria in terms of what the agent must achieve.",
            title='SuccessCriteriaOutputVsAgentVoice',
        ),
    ]
    success_failure_independence_statement_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the statement clarifying that success and failure criteria are independent evaluations. Prevents models from treating them as inverses of each other.\nTrue or false value',
            title='SuccessCriteriaSuccessFailureIndependenceStatementVisible',
        ),
    ]
    verification_guidance_suffix_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render the verification guidance suffix after evidence. Off by default. When enabled, reminds the model that some criteria are mechanically verifiable while others require judgment.\nTrue or false value',
            title='SuccessCriteriaVerificationGuidanceSuffixVisible',
        ),
    ]
    multi_criteria_relationship: Annotated[
        SuccessCriteriaMultiCriteriaRelationship,
        Field(
            description="How multiple success criteria relate to each other. 'independent_blocks' renders each criterion as a standalone block. 'numbered_dimensions' renders criteria as numbered evaluation dimensions. Only applies when criteria count exceeds one.\nHow multiple success criteria relate to each other. 'independent_blocks' renders each criterion as a standalone block. 'numbered_dimensions' numbers criteria as dimensions of a single quality assessment.",
            title='SuccessCriteriaMultiCriteriaRelationship',
        ),
    ]


class FailureCriteriaStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    section_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the failure criteria section at all. When false, the entire section is suppressed regardless of other settings.\nTrue or false value',
            title='FailureCriteriaSectionVisible',
        ),
    ]
    max_entries_rendered: Annotated[
        Integer,
        Field(
            default_factory=lambda: Integer(0),
            description='Maximum number of failure criteria entries to render. Zero means render all entries without limit.\nWhole number value',
            title='FailureCriteriaMaxEntriesRendered',
        ),
    ]
    abort_stance_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description="Whether to render the behavioral preamble that reframes abort as the correct action when failure conditions are detected. Sets the model's stance before individual failure modes are listed.\nTrue or false value",
            title='FailureCriteriaAbortStancePreambleVisible',
        ),
    ]
    cite_definition_and_evidence_postscript_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render the postscript connecting definition/evidence hierarchy to return_format reporting. Off by default — only needed when the reporting structure is complex.\nTrue or false value',
            title='FailureCriteriaCiteDefinitionAndEvidencePostscriptVisible',
        ),
    ]
    check_before_and_during_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render the generic temporal instruction about checking failure conditions before starting and monitoring throughout. Off by default.\nTrue or false value',
            title='FailureCriteriaCheckBeforeAndDuringVisible',
        ),
    ]
    abort_stance_variant: Annotated[
        FailureCriteriaAbortStanceVariant | None,
        Field(
            description="Selects the behavioral posture for abort conditions. 'obligation' frames stopping as a duty (MUST stop). 'permission' frames stopping as the correct action (the right thing to do). Governs both preamble and definition label variants.\nFailure criteria behavioral posture. 'obligation' frames stopping as a duty — the agent MUST stop when conditions are met. 'permission' frames stopping as the correct action — the agent is allowed to stop rather than forcing bad output.",
            title='FailureCriteriaAbortStanceVariant',
        ),
    ] = 'obligation'


class OutputStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_embed: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to inline the output schema content directly in the prompt. When true, the full schema is embedded. When false, only a path reference is rendered.\nTrue or false value',
            title='OutputSchemaEmbed',
        ),
    ]
    directory_location_variant: Annotated[
        OutputDirectoryLocationVariant,
        Field(
            description="Selects how the output directory location is declared. 'standard' states the directory path. 'with_boundary' adds an explicit boundary constraint that all files must be within the directory.\nHow output directory location renders. 'standard' states the directory path plainly. 'with_boundary' adds a confinement statement restricting output to that directory and its children.",
            title='OutputDirectoryLocationVariant',
        ),
    ]


class WritingOutputStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    transition_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the transition sentence connecting from the instructions section to the output mechanics section.\nTrue or false value',
            title='WritingOutputTransitionPreambleVisible',
        ),
    ]
    tool_mandate_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the tool exclusivity mandate establishing that output flows through exactly one tool with no exceptions.\nTrue or false value',
            title='WritingOutputToolMandateVisible',
        ),
    ]
    heredoc_explanation_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render the heredoc syntax explanation. Off by default. Only needed when agents mangle heredoc delimiters in their tool invocations.\nTrue or false value',
            title='WritingOutputHeredocExplanationVisible',
        ),
    ]


class ReturnFormatStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files_vs_status_explanation_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the explanation of the two-channel model where work products go to files and the return carries a status signal.\nTrue or false value',
            title='ReturnFormatFilesVsStatusExplanationPreambleVisible',
        ),
    ]
    token_must_be_first_word_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the protocol preamble establishing that the return token must appear as the first word and is parsed programmatically.\nTrue or false value',
            title='ReturnFormatTokenMustBeFirstWordPreambleVisible',
        ),
    ]
    report_all_metrics_postscript_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the metrics obligation postscript reminding the agent to report all specified metrics for its return state.\nTrue or false value',
            title='ReturnFormatReportAllMetricsPostscriptVisible',
        ),
    ]
    abort_vs_failure_distinction_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the semantic distinction between ABORT and FAILURE. Conditional on ABORT being a valid status token for this agent.\nTrue or false value',
            title='ReturnFormatAbortVsFailureDistinctionPreambleVisible',
        ),
    ]
    honest_failure_over_dubious_success_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the failure honesty preamble granting explicit permission to return a clean FAILURE rather than a dubious SUCCESS.\nTrue or false value',
            title='ReturnFormatHonestFailureOverDubiousSuccessPreambleVisible',
        ),
    ]
    track_metrics_as_you_work_postscript_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the retroactive orientation postscript establishing that return requirements imply tracking requirements throughout execution.\nTrue or false value',
            title='ReturnFormatTrackMetricsAsYouWorkPostscriptVisible',
        ),
    ]
    do_not_fabricate_metrics_postscript_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(True),
            description='Whether to render the accuracy clause requiring the agent to report actual metrics from execution rather than fabricating values to match the expected format.\nTrue or false value',
            title='ReturnFormatDoNotFabricateMetricsPostscriptVisible',
        ),
    ]
    failure_cross_reference_preamble_visible: Annotated[
        Boolean,
        Field(
            default_factory=lambda: Boolean(False),
            description='Whether to render a cross-reference to the failure_criteria section. Off by default. When enabled, connects the return protocol to the failure conditions defined elsewhere.\nTrue or false value',
            title='ReturnFormatFailureCrossReferencePreambleVisible',
        ),
    ]


class AgentOutputStructure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identity: Annotated[
        IdentityStructure,
        Field(
            description='Structure controls for the identity section. Field ordering, declaration fusion, and visibility toggles for optional prose.',
            title='IdentityStructure',
        ),
    ]
    security_boundary: Annotated[
        SecurityBoundaryStructure,
        Field(
            description='Structure controls for the security boundary section. Visibility toggles, workspace path fusion, and framing variant selector.',
            title='SecurityBoundaryStructure',
        ),
    ]
    critical_rules: Annotated[
        CriticalRulesStructure,
        Field(
            description='Structure controls for the critical rules section. Visibility toggles for each rule, presentation format, and hierarchy mode.',
            title='CriticalRulesStructure',
        ),
    ]
    instructions: Annotated[
        InstructionsStructure,
        Field(
            description='Structure controls for the instructions section. Heading variant, mode infrastructure, preamble components, step structure, closer, and scaffolding tier.',
            title='InstructionsStructure',
        ),
    ]
    examples: Annotated[
        ExamplesStructure,
        Field(
            description='Structure controls for the examples section. Preamble visibility, group heading suppression, override toggles with conditional override values, and framing sentence toggle.',
            title='ExamplesStructure',
        ),
    ]
    constraints: Annotated[
        ConstraintsStructure,
        Field(
            description='Structure controls for the constraints section. Master visibility, entry limit, visibility toggles, and variant selectors conditional on their paired visibility toggle.',
            title='ConstraintsStructure',
        ),
    ]
    anti_patterns: Annotated[
        AntiPatternsStructure,
        Field(
            description='Structure controls for the anti-patterns section. Master visibility, entry limit, preamble and distinction toggles.',
            title='AntiPatternsStructure',
        ),
    ]
    success_criteria: Annotated[
        SuccessCriteriaStructure,
        Field(
            description='Structure controls for the success criteria section. Variant selectors for definition framing, evidence framing, and transition style. Voice, evidence handling, and multi-criteria relationship.',
            title='SuccessCriteriaStructure',
        ),
    ]
    failure_criteria: Annotated[
        FailureCriteriaStructure,
        Field(
            description='Structure controls for the failure criteria section. Master visibility, entry limit, visibility toggles, and abort stance variant conditional on preamble visibility.',
            title='FailureCriteriaStructure',
        ),
    ]
    output: Annotated[
        OutputStructure,
        Field(
            description='Structure controls for the output section. Schema embedding toggle and directory location variant selector.',
            title='OutputStructure',
        ),
    ]
    writing_output: Annotated[
        WritingOutputStructure,
        Field(
            description='Structure controls for the writing output section. Visibility toggles for transition preamble, tool mandate, and heredoc explanation.',
            title='WritingOutputStructure',
        ),
    ]
    return_format: Annotated[
        ReturnFormatStructure,
        Field(
            description='Structure controls for the return format section. Visibility toggles for protocol components, metrics obligations, and cross-references.',
            title='ReturnFormatStructure',
        ),
    ]
